DROP DATABASE AGENDA_MAIS;
CREATE DATABASE AGENDA_MAIS;
USE AGENDA_MAIS;

CREATE TABLE TB_LOGIN_MEDICO(
id int auto_increment,
USUARIO varchar(15) NOT NULL,
SENHA VARCHAR(10) NOT NULL,
PRIMARY KEY(id)
);
CREATE TABLE TB_LOGIN_ASSISTENTE(
id int auto_increment,
USUARIO varchar(15) NOT NULL,
SENHA VARCHAR(10) NOT NULL,
PRIMARY KEY(id)
);
CREATE TABLE TB_LOGIN_ADM(
id int auto_increment,
USUARIO varchar(15) NOT NULL,
SENHA VARCHAR(10) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE TB_LOGIN_PACIENTE(
id int auto_increment,
SUS INT(15) NOT NULL,
SENHA VARCHAR(10) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE TB_ENDERECO(
COD_ENDERECO INT AUTO_INCREMENT,
RUA VARCHAR(30) NOT NULL,
BAIRRO VARCHAR(15) NOT NULL,
CIDADE VARCHAR(15) NOT NULL,
ESTADO VARCHAR(2) NOT NULL,
CEP VARCHAR(9) NOT NULL,
NUMERO INT(7) NOT NULL,

PRIMARY KEY(COD_ENDERECO)
);

CREATE TABLE TB_PACIENTE(
SUS INT(20) UNIQUE,
NOME VARCHAR(50) NOT NULL,
SOBRENOME VARCHAR(50) NOT NULL,
CPF VARCHAR(11) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
SEXO VARCHAR(1) NOT NULL,
NUMERO1 VARCHAR(20) NOT NULL,
NUMERO2 VARCHAR(20),
COD_ENDERECO INT not null,
PRIMARY KEY(SUS),
CONSTRAINT FOREIGN KEY (COD_ENDERECO) REFERENCES TB_ENDERECO(COD_ENDERECO)
);

CREATE TABLE TB_ASSISTENTE(
COD_ASSIST INT AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
CPF VARCHAR(11) UNIQUE NOT NULL,
EMAIL VARCHAR(50) NOT NULL,	
ID_UNIDADE INT(15) NOT NULL,
ID_LOGIN INT(15) NOT NULL,
NUMERO1 VARCHAR(20) NOT NULL,
NUMERO2 VARCHAR(20),
COD_ENDERECO INT,
PRIMARY KEY(COD_ASSIST),
CONSTRAINT FOREIGN KEY (ID_LOGIN) REFERENCES TB_LOGIN_ASSISTENTE(id),
CONSTRAINT FOREIGN KEY (COD_ENDERECO) REFERENCES TB_ENDERECO(COD_ENDERECO)
);

CREATE TABLE TB_ADMINISTRADOR(
COD_ADM INT AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,	
ID_LOGIN INT(15) NOT NULL,
PRIMARY KEY(COD_ADM),
CONSTRAINT FOREIGN KEY (ID_LOGIN) REFERENCES TB_LOGIN_ADM(id)
);




CREATE TABLE TB_UNIDADE(
COD_UNIDADE INT(15) PRIMARY KEY AUTO_INCREMENT,
NOME_UNIDADE VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL
);

 CREATE TABLE TB_MEDICOS(
COD_MED INT AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
CPF VARCHAR(11)UNIQUE NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
SEXO VARCHAR(1) NOT NULL,
ESPECIALIDADE VARCHAR(30) NOT NULL,
id_unidade int(15) NOT NULL,
id_login int(15) NOT NULL,
NUMERO1 VARCHAR(20) NOT NULL,
NUMERO2 VARCHAR(20),
COD_ENDERECO INT,
PRIMARY KEY(COD_MED),
CONSTRAINT FOREIGN KEY (id_login) REFERENCES TB_LOGIN_MEDICO(id),
CONSTRAINT FOREIGN KEY (COD_ENDERECO) REFERENCES TB_ENDERECO(COD_ENDERECO),
CONSTRAINT FOREIGN KEY (id_unidade) REFERENCES TB_UNIDADE(COD_UNIDADE)
 );
 
 CREATE TABLE TB_CONSULTA(
COD_CONSULTA INT AUTO_INCREMENT,
DIA VARCHAR(15),
UNIDADE VARCHAR (100),
ESPECIALIDADE VARCHAR (80),
HORARIO VARCHAR(15),
SITUACAO VARCHAR(4) DEFAULT 'true',
SUS INT(15),
PRIMARY KEY(COD_CONSULTA),
CONSTRAINT FOREIGN KEY (SUS) REFERENCES TB_PACIENTE (SUS)
 );
 
 CREATE TABLE TB_GUIA(
COD_GUIA INT AUTO_INCREMENT,
PRIMARY KEY(COD_GUIA)
 );
 
CREATE TABLE TB_ESPECIALIDADE(
COD_ESP INT PRIMARY KEY AUTO_INCREMENT,
ESPECIALIDADE VARCHAR(100) NOT NULL
);

insert into tb_login_adm(usuario,senha)
values('leonardo','1234');


insert into tb_administrador(nome,email,id_login)
values('Leonardo Albuquerque', 'leonardo@gmail.com',1);


    
INSERT INTO TB_UNIDADE(NOME_UNIDADE, TELEFONE)
VALUES('UBS III COHAB II ALTO DA COLINA', '1141436429');

INSERT INTO TB_UNIDADE(NOME_UNIDADE, TELEFONE)
VALUES('UBS III COHAB ITAPEVI', '1141435465');

INSERT INTO TB_UNIDADE(NOME_UNIDADE, TELEFONE)
VALUES('UBS III SANTA RITA ', '1141421938');

INSERT INTO TB_UNIDADE(NOME_UNIDADE, TELEFONE)
VALUES('UBS III SANTA RITA II', '1141435462');

INSERT INTO TB_UNIDADE(NOME_UNIDADE, TELEFONE)
VALUES('UBS IV DR NICANOR ANTONIO ABREU DE OLIVERA','1141435459');

INSERT INTO TB_UNIDADE(NOME_UNIDADE, TELEFONE)
VALUES('UNIDADE DE SAUDE DA FAMILIA AMBUITA	','1141448295');

INSERT INTO TB_UNIDADE(NOME_UNIDADE, TELEFONE)
VALUES('UNIDADE DE SAUDE DA FAMILIA CHACARA SANTA CECILIA	','1147737175');


INSERT INTO TB_UNIDADE(NOME_UNIDADE, TELEFONE)
VALUES('UNIDADE DE SAUDE DA FAMILIA JARDIM ROSEMEIRE','1142053365');

INSERT INTO TB_UNIDADE(NOME_UNIDADE, TELEFONE)
VALUES('UNIDADE DE SAUDE DA FAMILIA JD BRIQUET','1142052861');

INSERT INTO TB_UNIDADE(NOME_UNIDADE, TELEFONE)
VALUES('UNIDADE DE SAUDE DA FAMILIA JD VITAPOLIS','1142054870');

INSERT INTO TB_UNIDADE(NOME_UNIDADE, TELEFONE)
VALUES('UNIDADE DE SAUDE DA FAMILIA PARQUE SUBURBANO','1142053365');


INSERT INTO TB_UNIDADE(NOME_UNIDADE, TELEFONE)
VALUES('UNIDADE DE SAUDE DA FAMILIA VILA GIOIA	','1142053365');

INSERT INTO TB_endereco (rua,bairro,cidade,estado,cep,numero)
VALUES('rua','bairro2' ,'itapevi', 'sp', 11232321,12);

UPDATE tb_endereco  set cep = '565656565',rua='fdvx', bairro='jshfjks', cidade='fdsfs', numero =1  where cod_endereco = 5;

select * from tb_endereco;

SELECT sus from tb_login_paciente where sus =99 and senha = '99';


select * from tb_login_paciente;

select usuario from tb_login_medico where usuario = '66' and senha= '66';

SELECT * from tb_paciente;

INSERT INTO TB_PACIENTE(SUS,NOME,SOBRENOME,CPF,EMAIL,SEXO,NUMERO1,NUMERO2,COD_ENDERECO)VALUES (8,'dd','ddss','46637919802','fdgfd@hghgh.com','F','12','4243432423',2);





SELECT pac.email,ende.cep, ende.rua, ende.bairro, ende.cidade,ende.numero,pac.numero1,pac.numero2 
    from tb_paciente pac inner join tb_endereco ende on ende.cod_endereco = pac.cod_endereco
     where pac.sus = ?;
update  tb_paciente set numero1= '1141426175' where SUS = 12;

UPDATE tb_endereco  set cep = ?,rua=?, bairro=?, cidade=?, numero =?  where cod_endereco = ?;
UPDATE tb_endereco  set cep = '87484234',rua='dfs', bairro='ffff', cidade='tt', numero = 2  where cod_endereco = 2;