CREATE DATABASE AGENDAMAISRAPIDO;
DROP DATABASE AGENDAMAISRAPIDO;
USE AGENDAMAISRAPIDO;

CREATE TABLE TB_LOGINUSUARIO(
cod INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(40) NOT NULL,
sobrenome VARCHAR(40) NOT NULL,
email VARCHAR(50)NOT NULL,
senha VARCHAR(30)NOT NULL,
senha2 VARCHAR(30)NOT NULL,
cargo VARCHAR(50)NOT NULL,
nomeassistencia VARCHAR(50)NOT NULL,
endereco VARCHAR(100)NOT NULL,
cep VARCHAR(20)NOT NULL,
cnpj VARCHAR(20)NOT NULL,
cpf VARCHAR(20)NOT NULL,
tel VARCHAR(20)NOT NULL,
tel2 VARCHAR(20)NOT NULL);


INSERT into TB_LOGINUSUARIO(nome,sobrenome,email,senha,senha2,cargo,nomeassistencia,endereco,cep,cnpj,cpf,tel,tel2)
VALUES
('Marcelo','pelaes','marcelo@gmail.com','123','123','professor','saude','rua tal','06602','123456','40183162838','953860078','963811062');
/*SELECT * FROM TB_LOGINUSUARIO;*/

CREATE TABLE TB_LOGINADM(
cod INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(40) NOT NULL,
sobrenome VARCHAR(40) NOT NULL,
nomedeadm VARCHAR(40) NOT NULL,
email VARCHAR(50)NOT NULL,
senha VARCHAR(30)NOT NULL,
senha2 VARCHAR(30)NOT NULL,
cpf VARCHAR(20)NOT NULL);

INSERT into TB_LOGINADM(nome,sobrenome,nomedeadm,email,senha,senha2,cpf)
VALUES
('Leone','Fragoso','ROOT','leonefelip@gmail.com','1234','1234','40183162838');
/*SELECT * FROM TB_LOGINADM;*/

CREATE TABLE TB_LOGINMEDICO(
cod INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(40) NOT NULL,
sobrenome VARCHAR(40) NOT NULL,
endereco VARCHAR(100)NOT NULL,
cep VARCHAR(20)NOT NULL,
email VARCHAR(50)NOT NULL,
senha VARCHAR(30)NOT NULL,
senha2 VARCHAR(30)NOT NULL,
cargo VARCHAR(50)NOT NULL,
RG VARCHAR(12)NOT NULL,
cnpj VARCHAR(20)NOT NULL,
crm VARCHAR(20)NOT NULL,
tel VARCHAR(20)NOT NULL,
tel2 VARCHAR(20)NOT NULL);

CREATE TABLE TB_LOGINPACIENTE(
cod INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(40) NOT NULL,
sobrenome VARCHAR(40) NOT NULL,
endereco VARCHAR(100)NOT NULL,
cep VARCHAR(20)NOT NULL,
email VARCHAR(50)NOT NULL,
senha VARCHAR(30)NOT NULL,
senha2 VARCHAR(30)NOT NULL,
cpf VARCHAR(11)NOT NULL,
RG VARCHAR(12)NOT NULL,
tel VARCHAR(20)NOT NULL,
tel2 VARCHAR(20)NOT NULL);

CREATE TABLE TB_CONSULTA(
cod INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(40) NOT NULL,
especialista VARCHAR(40)NOT NULL,
dia VARCHAR(15)NOT NULL,/*PERGUNTAR*/
email VARCHAR(50)NOT NULL,
tel VARCHAR(20)NOT NULL,
tel2 VARCHAR(20)NOT NULL);









